# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
assistant_id: 20250409-155242-plain-burbot

# Configuration for Rasa NLU.
language: "es"  # Cambiado a español

pipeline:
- name: SpacyNLP
  model: "es_core_news_md"    # Usamos el modelo de spaCy para español
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Configuration for Rasa Core.
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
